---
description: "Test Asset"
labels:
  example: "custom"      
annotations:
  test: "value"
builds:
- platform: "OSX"
  arch: "amd64"
  asset_filename: "#{repo}_#{version}_darwin_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  -  "entity.system.os == 'darwin'"
  -  "entity.system.arch == 'amd64'"

